// Papers configuration - flat list. Tags are used for paper search/filtering.
const PAPERS_CONFIG = [
  {
    url: "https://openreview.net/forum?id=oreET6Wz52",
    pdfUrl: "https://openreview.net/forum?id=oreET6Wz52",
    codeUrl: "https://github.com/yifu-ding/MoE-Slimming",
    detailUrl: "",
    imageUrl: "src/papers/imgs/compression-large-language-models.png",
    venue: "ICML 2026 Spotlight",
    year: 2026,
    title: "Attribution-Guided and Coverage-Maximized Pruning for Structural MoE Compression",
    authors: "Yifu Ding, Jiacheng Wang, Ge Yang, Yongcheng Jing, Jinyang Guo, Xianglong Liu, Dacheng Tao",
    description: "Structurally compresses MoE models by pruning channels rather than whole experts, using attribution-guided coverage maximization to preserve important expert information.",
    selected: true,
    tags: ["LLM","MoE","Pruning","Quantization", "Language Model", "Training-free"]
  },
  {
    url: "https://arxiv.org/abs/2602.02544",
    pdfUrl: "https://arxiv.org/abs/2602.02544",
    codeUrl: "https://github.com/wenhao728/spa-cache",
    detailUrl: "",
    imageUrl: "src/papers/imgs/singular-cache-overview.png",
    venue: "ICML 2026",
    year: 2026,
    title: "SPA-Cache: Singular Proxies for Adaptive Caching in Diffusion Language Models",
    authors: "Wenhao Sun, Rong-Cheng Tu, Yifu Ding, Zhao Jin, Jingyi Liao, Yongcheng Jing, Dacheng Tao",
    description: "SPA-Cache accelerates diffusion language model decoding with a singular proxy for update-critical tokens and adaptive layer-wise update budgets.",
    selected: true,
    tags: ["LLM","Diffusion","Caching","Acceleration", "Language Model", "Training-free"]
  },
  {
    url: "https://arxiv.org/abs/2409.16694",
    pdfUrl: "https://arxiv.org/abs/2409.16694",
    codeUrl: "",
    detailUrl: "",
    imageUrl: "src/papers/imgs/llm-quant-survey.png",
    venue: "Neural Networks",
    year: 2026,
    title: "A Survey of Low-Bit Large Language Models: Basics, Systems, and Algorithms",
    authors: "Ruihao Gong, Yifu Ding, Zining Wang, Chengtao Lv, Xingyu Zheng, Jinyang Du, Haotong Qin, Jinyang Guo, Michele Magno, Xianglong Liu",
    description: "This survey reviews low-bit quantization for large language models, covering core principles, data formats, system support, and algorithmic methods.",
    selected: true,
    tags: ["LLM","Survey","Quantization"]
  },
  {
    url: "https://proceedings.neurips.cc/paper_files/paper/2024/file/9f4cc62d0632911c63163ea3d9ec19bd-Paper-Datasets_and_Benchmarks_Track.pdf",
    pdfUrl: "https://proceedings.neurips.cc/paper_files/paper/2024/file/9f4cc62d0632911c63163ea3d9ec19bd-Paper-Datasets_and_Benchmarks_Track.pdf",
    codeUrl: "https://github.com/AboveParadise/LLMCBench",
    detailUrl: "",
    imageUrl: "src/papers/imgs/llmcbench.png",
    venue: "NeurIPS 2024 Spotlight",
    year: 2024,
    title: "LLMCBench: Benchmarking Large Language Model Compression for Efficient Deployment",
    authors: "Ge Yang, Changyi He, Jinyang Guo, Jiannan Wu, Yifu Ding, Aishan Liu, Haotong Qin, Pengliang Ji, Xianglong Liu",
    description: "LLMCBench evaluates 7 compression methods across 18 LLM architectures, 11 datasets, and 3 deployment platforms for efficient deployment.",
    tags: ["LLM","Benchmark","Quantization", "Pruning"]
  },
  {
    url: "https://dl.acm.org/doi/10.5555/3692070.3692743",
    pdfUrl: "https://openreview.net/pdf?id=sCGRhnuMUJ",
    codeUrl: "",
    detailUrl: "",
    imageUrl: "src/papers/imgs/jsq-overview.png",
    venue: "ICML 2024",
    year: 2024,
    title: "Compressing Large Language Models by Joint Sparsification and Quantization",
    authors: "",
    description: "",
    tags: ["LLM","Pruning","Quantization","Language Model"]
  },
  {
    url: "https://openreview.net/pdf?id=NCYBdRCpw1",
    pdfUrl: "https://openreview.net/pdf?id=NCYBdRCpw1",
    codeUrl: "",
    detailUrl: "",
    imageUrl: "src/papers/imgs/da-kd.png",
    venue: "ICML 2025",
    year: 2025,
    title: "DA-KD: Difficulty-Aware Knowledge Distillation for Efficient Large Language Models",
    authors: "Changyi He, Yifu Ding, Jinyang Guo, Ruihao Gong, Haotong Qin, Xianglong Liu",
    description: "DA-KD reduces distillation cost by dynamically selecting training samples based on difficulty and stabilizing optimization with bidirectional discrepancy loss.",
    selected: true,
    tags: ["LLM","Knowledge Distillation", "Language Model", "Mid-Training"]
  },
  {
    url: "https://arxiv.org/pdf/2511.15690",
    pdfUrl: "https://arxiv.org/pdf/2511.15690",
    codeUrl: "https://github.com/ModelTC/MoDES",
    detailUrl: "",
    imageUrl: "src/papers/imgs/modes-overview.png",
    venue: "CVPR 2026",
    year: 2026,
    title: "MoDES: Accelerating Mixture-of-Experts Multimodal Large Language Models via Dynamic Expert Skipping",
    authors: "Yushi Huang, Zining Wang, Zhenyu Yuan, Yifu Ding, Ruihao Gong, Jinyang Guo, Xianglong Liu, Jun Zhang",
    description: "MoDES accelerates multimodal LLM inference with training-free expert skipping driven by modality heterogeneity.",
    tags: ["LLM","MoE","Expert Skipping", "Multimodal", "Multimodal Understanding", "Training-free"]
  },
  {
    url: "https://arxiv.org/pdf/2402.11960",
    detailUrl: "",
    imageUrl: "src/papers/imgs/db-llm.png",
    venue: "ACL Findings 2024",
    year: 2024,
    title: "DB-LLM: Accurate Dual-Binarization for Efficient LLMs",
    tags: ["LLM","Binarization","Quantization", "Language Model"]
  },
  {
    url: "https://aclanthology.org/2025.acl-long.550.pdf",
    pdfUrl: "https://aclanthology.org/2025.acl-long.550.pdf",
    codeUrl: "https://github.com/yifu-ding/DPTS",
    detailUrl: "",
    imageUrl: "src/papers/imgs/dpts-small.png",
    venue: "ACL 2025",
    year: 2025,
    title: "Dynamic Parallel Tree Search for Efficient LLM Reasoning",
    authors: "Yifu Ding, Wentao Jiang, Shunyu Liu, Yongcheng Jing, Jinyang Guo, Yingjie Wang, Jing Zhang, Zengmao Wang, Ziwei Liu, Bo Du, Xianglong Liu, Dacheng Tao",
    description: "DPTS accelerates Tree of Thoughts reasoning by reducing redundant exploration and focus switching, achieving 2-4x speedups on Qwen-2.5 and Llama-3.",
    selected: true,
    tags: ["LLM","Tree of Thoughts","Reasoning", "Code Generation", "Mathematical Reasoning", "Training-free"]
  },
  {
    url: "https://arxiv.org/pdf/2505.11497",
    pdfUrl: "https://arxiv.org/pdf/2505.11497",
    codeUrl: "https://github.com/ModelTC/QVGen",
    detailUrl: "",
    imageUrl: "src/papers/imgs/qvgen.png",
    venue: "ICLR 2026",
    year: 2026,
    title: "QVGen: Pushing the Limit of Quantized Video Generative Models",
    authors: "Yushi Huang, Ruihao Gong, Jing Liu, Yifu Ding, Chengtao Lv, Haotong Qin, Jun Zhang",
    description: "QVGen enables extremely low-bit quantization-aware training for video diffusion models while preserving near full-precision generation quality at 4-bit.",
    selected: true,
    tags: ["Video Generation","Diffusion","PTQ","Quantization"]
  },
  {
    url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Lv_PTQ4SAM_Post-Training_Quantization_for_Segment_Anything_CVPR_2024_paper.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/ptq4sam.png",
    venue: "CVPR 2024",
    year: 2024,
    title: "PTQ4SAM: Post-Training Quantization for Segment Anything",
    tags: ["SAM","PTQ","Segmentation","Quantization"]
  },
  {
    url: "https://openaccess.thecvf.com/content/CVPR2024/papers/Ding_Reg-PTQ_Regression-specialized_Post-training_Quantization_for_Fully_Quantized_Object_Detector_CVPR_2024_paper.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/reg-ptq.png",
    venue: "CVPR 2024",
    year: 2024,
    title: "Reg-PTQ: Regression-Specialized Post-Training Quantization for Fully Quantized Object Detector",
    tags: ["Detection","PTQ","Regression","Quantization"]
  },
  {
    url: "https://openreview.net/pdf?id=3gamyee9Yh",
    pdfUrl: "https://proceedings.neurips.cc/paper_files/paper/2023/file/b2169d573d75ff90c7b12dc3a5fc2898-Paper-Conference.pdf",
    codeUrl: "https://github.com/htqin/QuantSR",
    detailUrl: "",
    imageUrl: "src/papers/imgs/quantsr.png",
    venue: "NeurIPS 2023 Spotlight",
    year: 2023,
    title: "QuantSR: Accurate Low-Bit Quantization for Efficient Image Super-Resolution",
    authors: "Haotong Qin, Yulun Zhang, Yifu Ding, Yi Liu, Xianglong Liu, Martin Danelljan, Fisher Yu",
    description: "QuantSR uses deep dynamic quantization with parameter redistribution for accurate low-bit image super-resolution.",
    tags: ["Super-Resolution","PTQ","Quantization"]
  },
  {
    url: "https://arxiv.org/pdf/2303.14341",
    detailUrl: "",
    imageUrl: "src/papers/imgs/apq-vit-towards.png",
    venue: "CVPR 2022",
    year: 2022,
    title: "Towards Accurate Post-Training Quantization for Vision Transformer",
    tags: ["ViT","PTQ","Quantization"]
  },
  {
    url: "https://arxiv.org/pdf/2109.00212",
    detailUrl: "",
    imageUrl: "src/papers/imgs/dsg-pami-overview.png",
    venue: "IEEE TPAMI 2023",
    year: 2023,
    title: "Diverse Sample Generation: Pushing the Limit of Generative Data-Free Quantization",
    tags: ["Data-free","CNN","PTQ","Quantization"]
  },
  {
    url: "https://openaccess.thecvf.com/content/CVPR2022W/ArtOfRobust/papers/Chen_An_Empirical_Study_of_Data-Free_Quantizations_Tuning_Robustness_CVPRW_2022_paper.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/an-emperical-study-of-datafree.png",
    venue: "CVPR Workshop 2022",
    year: 2022,
    title: "An Empirical Study of Data-Free Quantization's Tuning Robustness",
    tags: ["Data-free","CNN","PTQ","Quantization"]
  },
  {
    url: "https://arxiv.org/abs/2103.01049",
    detailUrl: "",
    imageUrl: "src/papers/imgs/dsg-cvpr-overview.png",
    venue: "CVPR 2021",
    year: 2021,
    title: "Diversifying Sample Generation for Accurate Data-Free Quantization",
    tags: ["Data-free","Quantization","CNN","PTQ"]
  },
  {
    url: "https://proceedings.mlr.press/v202/qin23b/qin23b.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bibench-clear.png",
    venue: "ICML 2023",
    year: 2023,
    title: "BiBench: Benchmarking and Analyzing Network Binarization",
    tags: ["Benchmark","Binarization"]
  },
  {
    url: "https://arxiv.org/pdf/2211.06987",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bifsmn-v2.png",
    venue: "IEEE TNNLS 2024",
    year: 2024,
    title: "BiFSMNv2: Pushing Binary Neural Networks for Keyword Spotting to Real-Network Performance",
    tags: ["Keyword Spotting","Binarization"]
  },
  {
    url: "https://arxiv.org/pdf/2109.12338",
    detailUrl: "",
    imageUrl: "src/papers/imgs/distribution-sensitive-overview.png",
    venue: "IJCV 2022",
    year: 2022,
    title: "Distribution-Sensitive Information Retention for Accurate Binary Neural Network",
    tags: ["Binarization","CNN"]
  },
  {
    url: "https://openreview.net/pdf?id=EtKEzgslVg5",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bibert.png",
    venue: "ICLR 2022",
    year: 2022,
    title: "BiBERT: Accurate Fully Binarized BERT",
    tags: ["BERT","Binarization"]
  },
  {
    url: "https://www.ijcai.org/proceedings/2022/0603.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bifsmn-overview.png",
    venue: "IJCAI 2021",
    year: 2021,
    title: "BiFSMN: Binary Neural Network for Keyword Spotting",
    tags: ["Keyword Spotting","Binarization","FSMN"]
  },
  {
    url: "https://openreview.net/pdf?id=9QLRCVysdlO",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bipointnet.png",
    venue: "ICLR 2021",
    year: 2021,
    title: "BiPointNet: Binary Neural Network for Point Clouds",
    tags: ["Point Clouds","Binarization","PointNet"]
  },
  {
    url: "https://openaccess.thecvf.com/content/ICCV2025W/ECLR/papers/Du_Low-bit_FlashAttention_Accelerated_Operator_Design_Based_on_Triton_ICCVW_2025_paper.pdf",
    pdfUrl: "https://openaccess.thecvf.com/content/ICCV2025W/ECLR/papers/Du_Low-bit_FlashAttention_Accelerated_Operator_Design_Based_on_Triton_ICCVW_2025_paper.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/du-low-bit-flash-attention-overview.png",
    venue: "ECLR 2025 (ICCV Workshop)",
    year: 2025,
    title: "Low-Bit FlashAttention Accelerated Operator Design Based on Triton",
    authors: "Jinyang Du, Jinyang Guo, Yifu Ding",
    description: "A Triton-based mixed-precision FlashAttention operator integrates quantization, dequantization, and attention for efficient low-bit inference.",
    tags: ["Attention","Triton Kernel","Quantization"]
  },
  {
    url: "https://arxiv.org/pdf/2604.03950",
    pdfUrl: "https://arxiv.org/pdf/2604.03950",
    codeUrl: "https://github.com/yifu-ding/MP-Sparse-Attn",
    detailUrl: "",
    imageUrl: "src/papers/imgs/diagonal-tailed-overview.png",
    venue: "EDGE @ CVPR 2026",
    year: 2026,
    title: "Diagonal-Tiled Mixed-Precision Attention for Efficient Low-Bit MXFP Inference",
    authors: "Yifu Ding, Xuan Zhang",
    description: "A Triton-based MXFP mixed-precision attention kernel for efficient and accurate low-bit attention inference on NVIDIA B200.",
    tags: ["Attention","Triton Kernel","Quantization","MXFP"]
  },
  {
    url: "https://arxiv.org/pdf/2604.03957",
    pdfUrl: "https://arxiv.org/pdf/2604.03957",
    codeUrl: "https://github.com/yifu-ding/BGEMM-CUDA",
    detailUrl: "",
    imageUrl: "src/papers/imgs/bwta-kernel.png",
    venue: "Submitted to IEEE-TPAMI under review",
    year: 2026,
    title: "BWTA: Accurate and Efficient Binarized Transformer by Algorithm-Hardware Co-Design",
    authors: "Yifu Ding, Xianglong Liu, Shiyao Jin, Jinyang Guo, Jiliang Lu",
    description: "Algorithm-hardware co-design with CUDA kernels for ultra-low-bit binary and ternary Transformer computation.",
    tags: ["Binarization","CUDA Kernel","Hardware","Transformer"]
  },
  {
    url: "https://openreview.net/forum?id=B2DRmwStm9",
    pdfUrl: "https://openreview.net/forum?id=B2DRmwStm9",
    detailUrl: "",
    imageUrl: "src/papers/imgs/qus-figure4.png",
    venue: "OpenReview",
    year: 2026,
    title: "QuS: Towards High-Performance EfficientViT on FPGA by Quantization and Streamline Co-Design",
    authors: "Yicheng Zeng, Yifu Ding, Jinyang Guo, Haotong Qin, Yifan Xu, Nianxin Li, Yao Guo, Xianglong Liu",
    description: "QuS co-designs DSP packing, low-buffer streamline, and distribution-aware quantization for high-performance ViT acceleration on FPGA.",
    tags: ["ViT","FPGA","Hardware","Quantization"]
  },
  {
    url: "https://arxiv.org/pdf/2505.18809",
    pdfUrl: "https://arxiv.org/pdf/2505.18809",
    codeUrl: "https://github.com/wenhao728/VORTA",
    detailUrl: "",
    imageUrl: "src/papers/imgs/vorta.png",
    venue: "NeurIPS 2025",
    year: 2025,
    title: "VORTA: Efficient Video Diffusion via Routing Sparse Attention",
    authors: "Wenhao Sun, Rong-Cheng Tu, Yifu Ding, Zhao Jin, Jingyi Liao, Shunyu Liu, Dacheng Tao",
    description: "VORTA accelerates video diffusion transformers using routing sparse attention for long-range dependencies, composing with other methods for large speedups.",
    selected: true,
    tags: ["Video Generation","Diffusion","Attention"]
  },
  {
    url: "https://www.ijcai.org/proceedings/2025/0059.pdf",
    pdfUrl: "https://www.ijcai.org/proceedings/2025/0059.pdf",
    codeUrl: "https://github.com/rstao-bjtu/QMDD",
    detailUrl: "",
    imageUrl: "src/papers/imgs/unlocking.png",
    venue: "IJCAI 2025",
    year: 2025,
    title: "Unlocking the Potential of Lightweight Quantized Models for Deepfake Detection",
    authors: "Renshuai Tao, Ziheng Qin, Yifu Ding, Chuangchuang Tan, Jiakai Wang, Wei Wang",
    description: "This work targets real-time edge deepfake detection with low-bit quantization, reducing compute and storage while preserving strong accuracy.",
    selected: true,
    tags: ["Deepfake","Image Detection","Quantization"]
  },
  {
    url: "https://openaccess.thecvf.com/content/CVPR2022/papers/Tao_Exploring_Endogenous_Shift_for_Cross-Domain_Detection_A_Large-Scale_Benchmark_and_CVPR_2022_paper.pdf",
    detailUrl: "",
    imageUrl: "src/papers/imgs/tao-exploring-endogenuous-shift-overview.png",
    venue: "CVPR 2022",
    year: 2022,
    title: "Exploring Endogenous Shift for Cross-Domain Detection: A Large-Scale Benchmark and Perturbation Suppression Network",
    tags: ["Image Detection","Benchmark","Domain Adaptation", "Cross-domain"]
  },
  {
    url: "https://doi.org/10.1109/TCSVT.2023.3250646",
    detailUrl: "",
    imageUrl: "src/papers/imgs/spatial-temporal-adaptive-overview.png",
    venue: "IEEE TCSVT 2021",
    year: 2021,
    title: "Spatio-Temporal Adaptive Network with Bidirectional Temporal Difference for Action Recognition",
    tags: ["Action Recognition","Domain Adaptation"]
  },
  {
    url: "https://dl.acm.org/doi/pdf/10.1145/3475724.3483603",
    detailUrl: "",
    pdfUrl: "https://dl.acm.org/doi/pdf/10.1145/3475724.3483603",
    imageUrl: "src/papers/imgs/advm-2021-overview.jpg",
    venue: "ACM MM 2021",
    year: 2021,
    title: "Improving Generalization of Deepfake Detection with Domain Adaptive Batch Normalization",
    tags: ["Deepfake","Image Detection","Domain Adaptation"]
  },
  {
    url: "https://ieeexplore.ieee.org/abstract/document/9428447",
    detailUrl: "",
    imageUrl: "src/papers/imgs/icme-2021-overview.jpg",
    venue: "ICME 2021",
    year: 2021,
    title: "Multi-Pretext Attention Network for Few-Shot Learning with Self-Supervision",
    tags: ["Few-shot Learning"]
  },
  {
    url: "https://arxiv.org/pdf/2103.00809",
    detailUrl: "",
    imageUrl: "src/papers/imgs/tmm-2021-oversampling-overview.jpg",
    venue: "IEEE TRANSACTIONS ON MULTIMEDIA 2021",
    year: 2021,
    title: "Over-Sampling De-Occlusion Attention Network for Prohibited Items Detection in Noisy X-Ray Images",
    tags: ["X-ray","Image Detection","De-occlusion"]
  },
  {
    url: "https://iccv.thecvf.com/virtual/2025/workshop/2785",
    detailUrl: "",
    imageUrl: "src/workshops/posters/eclr-iccv-2025.png",
    venue: "ICCV 2025",
    year: 2025,
    title: "ECLR'25: 2nd Workshop on Efficient Computing under Limited Resources: Visual Computing",
    tags: ["Workshop", "Efficient Computing"]
  },
  {
    url: "https://emclr-acmmm.github.io/",
    detailUrl: "",
    imageUrl: "src/workshops/posters/emclr-acmmm-2024.png",
    venue: "EMCLR 2024",
    year: 2024,
    title: "2024 1st International Workshop on Efficient Multimedia Computing under Limited Resources Organization",
    tags: ["Workshop","Efficient Computing"]
  }
];
