// Workshop card configuration.
const WORKSHOPS_CONFIG = [
  {
    url: "https://cvpr26-advml.github.io/",
    imageUrl: "src/workshops/posters/6th-advml-2026.jpg",
    series: "other",
    workshop: "AdvML",
    venue: "CVPR",
    time: "Jun 2026",
    timeZh: "2026年6月",
    location: "Denver, Colorado",
    locationZh: "美国科罗拉多州丹佛",
    title: "Adversarial Machine Learning on Computer Vision: Safety of Vision-Language Agents",
    titleZh: "计算机视觉对抗机器学习：视觉语言智能体安全"
  },
  {
    url: "https://glow-ijcai-2026.github.io/glow-ijcai-2026/",
    imageUrl: "src/workshops/posters/4th-glow-2026-ijcai.jpg",
    series: "glow",
    workshop: "GLOW",
    venue: "IJCAI",
    time: "Jun 2026",
    timeZh: "2026年6月",
    location: "Bremen, Germany",
    locationZh: "德国不来梅",
    title: "Generalizing from Limited Resources in the Open World",
    titleZh: "开放世界中的有限资源泛化"
  },
  {
    url: "https://eclr-workshop.github.io/",
    imageUrl: "src/workshops/posters/eclr-iccv-2025.png",
    series: "eclr",
    workshop: "ECLR",
    venue: "ICCV",
    time: "Oct 2025",
    timeZh: "2025年10月",
    location: "Honolulu, Hawaii",
    locationZh: "美国夏威夷檀香山",
    title: "Efficient Computing under Limited Resources: Visual Computing",
    titleZh: "有限资源下的高效计算：视觉计算"
  },
  {
    url: "https://glow-ijcai-2025.github.io/glow-ijcai-2025",
    imageUrl: "src/workshops/posters/3rd-glow-ijcai-2025.jpg",
    series: "glow",
    workshop: "GLOW",
    venue: "IJCAI",
    time: "Aug 2025",
    timeZh: "2025年8月",
    location: "Montreal, Canada",
    locationZh: "加拿大蒙特利尔",
    title: "Generalizing from Limited Resources in the Open World",
    titleZh: "开放世界中的有限资源泛化"
  },
  {
    url: "https://practical-dl.github.io/",
    imageUrl: "src/workshops/posters/4th-practicalDL-25.jpg",
    series: "practical",
    workshop: "Practical-DL",
    venue: "IJCAI",
    time: "Aug 2025",
    timeZh: "2025年8月",
    location: "Montreal, Canada",
    locationZh: "加拿大蒙特利尔",
    title: "Toward Robust Compressed Foundation Models in the Real World",
    titleZh: "面向真实世界鲁棒压缩基础模型的实用深度学习"
  },
  {
    url: "https://eclr-workshop.github.io/index_2024.html",
    imageUrl: "src/workshops/posters/emclr-acmmm-2024.png",
    series: "eclr",
    workshop: "EMCLR",
    venue: "ACM MM",
    time: "Oct 2024",
    timeZh: "2024年10月",
    location: "Melbourne, Australia",
    locationZh: "澳大利亚墨尔本",
    title: "Efficient Multimedia Computing under Limited Resources",
    titleZh: "有限资源下的高效多媒体计算"
  },
  {
    url: "https://glow-ijcai.github.io/",
    imageUrl: "src/workshops/posters/glow-ijcai-2024-poster.png",
    series: "glow",
    workshop: "GLOW",
    venue: "IJCAI",
    time: "Aug 2024",
    timeZh: "2024年8月",
    location: "Jeju, South Korea",
    locationZh: "韩国济州",
    title: "Generalizing from Limited Resources in the Open World",
    titleZh: "开放世界中的有限资源泛化"
  },
  {
    url: "https://sites.google.com/view/glow-ijcai-23",
    imageUrl: "src/workshops/posters/1st-glow.png",
    series: "glow",
    workshop: "GLOW",
    venue: "IJCAI",
    time: "Aug 2023",
    timeZh: "2023年8月",
    location: "Macao, S.A.R.",
    locationZh: "中国澳门",
    title: "Generalizing from Limited Resources in the Open World",
    titleZh: "开放世界中的有限资源泛化"
  },
  {
    url: "https://practical-dl.github.io/",
    imageUrl: "src/workshops/posters/3nd-PracticalDL-24.jpg",
    series: "practical",
    workshop: "Practical-DL",
    venue: "IEEE CAI",
    time: "Jun 2024",
    timeZh: "2024年6月",
    location: "Singapore",
    locationZh: "新加坡",
    title: "Towards Efficient and Reliable LLMs",
    titleZh: "面向高效可靠大语言模型的实用深度学习"
  },
  {
    url: "https://practical-dl.github.io/2023/index",
    imageUrl: "",
    series: "practical",
    workshop: "Practical-DL",
    venue: "AAAI",
    time: "Feb 2023",
    timeZh: "2023年2月",
    location: "Washington, D.C.",
    locationZh: "美国华盛顿特区",
    title: "Practical Deep Learning in the Wild",
    titleZh: "真实场景中的实用深度学习"
  },
  {
    url: "https://practical-dl.github.io/2022/index",
    imageUrl: "src/workshops/posters/1st-practicalDL-poster.jpg",
    series: "practical",
    workshop: "Practical-DL",
    venue: "AAAI",
    time: "Feb 2022",
    timeZh: "2022年2月",
    location: "Virtual",
    locationZh: "线上",
    title: "Practical Deep Learning in the Wild",
    titleZh: "真实场景中的实用深度学习"
  }
];
